-- ============================================================
-- AzzeroCO2 Energy - Enable Row Level Security on ALL tables
-- Must run BEFORE 003_rls_policies.sql
-- ============================================================

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE demands ENABLE ROW LEVEL SECURITY;
ALTER TABLE lighting_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE technology_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE tech_inputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE tech_outputs ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_technologies ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage_systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenario_tech_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE scenario_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE tech_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE nace_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
